# Generated by Django 5.1.3 on 2024-11-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastmenu',
            name='meal_picture',
            field=models.ImageField(blank=True, null=True, upload_to='meal_pictures/'),
        ),
        migrations.AlterField(
            model_name='fastmenu',
            name='food_category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SUPPER', 'Supper'), ('DRINKS', 'Drinks'), ('PASTRIES', 'Pastries')], max_length=30),
        ),
    ]
